project_id = "messenger"

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "exp://127.0.0.1:8081"
additional_redirect_urls = ["messenger://auth/callback"]
jwt_expiry = 3600
enable_signup = true

[realtime]
enabled = true

[storage]
enabled = true
file_size_limit = "25MiB"

